#!/bin/bash

base_cmd="$1"
full_cmd="do/$1"
shift

while true; do
    git ls-files -co --exclude-standard . | grep -v "^$base_cmd\$" \
        | entr -d "$full_cmd" "$@"
    if [ ${PIPESTATUS[2]} = 0 ]; then
        break
    fi
done
